### ISSUE TITLE
[Errore installazione] Configurazione database

### ISSUE THREAD

**Issue by cappe87** [UniCt-Easy/Easy-Uni.Co.#3]
Ciao a tutti,
installato easy e fatti gli aggiornamenti quando si prova a eseguire la configurazione tecnica, nella parte di creazione del database l'applicativo restituisce il seguente errore:
Errore non gestito (*)

Dettagli
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in metadatalibrary.QueryCreator.ColumnValues(DataTable T, String filter, String column, Boolean SQL)
   in Install.Frm_Install.CustomChangeTab(Int32 oldTab, Int32 newTab)
   in Install.Frm_Install.StandardChangeTab(Int32 step)
   in Install.Frm_Install.btnNext_Click(Object sender, EventArgs e)
   in System.Windows.Forms.Control.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ButtonBase.WndProc(Message& m)
   in System.Windows.Forms.Button.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

SO = windows server 2019 - MSSQL = SQL Express 2019

Grazie

**Comment by UniCt-Easy** [comment]
Ciao,
forse si sta tentando l'operazione con una copia non correttamente aggiornata di Easy. Subito dopo l'installazione, occorre avviare Easy senza eseguire l'autenticazione e lasciare che scarichi gli aggiornamenti da internet fino alla comparsa del messaggio "Aggiornamento Software OK". 
A quel punto, conviene riavviare il programma per essere sicuri di utilizzare tutte le componenti aggiornate e si può proseguire con la creazione del database e la configurazione tecnica.
Se invece questa operazione è stata già eseguita allora occorre verificare se qualcosa è andata storta in fase di creazione del dipartimento , che è sostanzialmente un utente di Sql Server proprietario dello schema delle tabelle con i dati del singolo dipartimento.
Le versioni di sistema operativo e Sql Server invece vanno bene
Fammi sapere come va
Gianni

**Comment by cappe87** [comment]
Per uso futuro:
nella configurazione tecnica, il database bisogna farlo creare all'applicativo e non farlo prima.
Quindi inseriti i dati di connessione cliccare su "crea nuovo database"
![easy](https://user-images.githubusercontent.com/6532945/74347452-66f36a00-4db1-11ea-800f-bf29a0219e27.png)

Grazie a Gianni che mi ha tempestivamente contattato per risolvere il problema.
