### ISSUE TITLE
14789 - Etichetta della prima coordinata del dettaglio viene parzialmente nascosta

### ISSUE THREAD

**Issue by giannismal** [UniCt-Easy/Easy-Uni.Co.#4]
Dall'Accademia di Santa Cecilia ci segnalano che l'etichetta della prima coordinata analitica viene nascosta dal group box
![Immagine](https://user-images.githubusercontent.com/61357331/81955176-0c64e680-960a-11ea-8be8-e873615f46dc.jpg)

**Comment by UniCt-Easy** [comment]
14789  Corretta la visualizzazione group box coordinate analitiche in dettagli fattura
